exec-once = qs -c noctalia-shell
exec-once = /home/hihity/func/hypr

env = GTK_USE_PORTAL,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NIRI_DISABLE_SECONDARY_SELECTION_SYNC,1
env = QT_QPA_PLATFORMTHEME,qt6ct

bind = SUPER, C, exec, kitty
binde = SUPER, F, killactive,
bind = SUPER, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = SUPER, E, exec, kitty -e yazi
bind = SUPER, A, fullscreen,
bind = SUPER, V, togglefloating
bind = SUPER, D, exec, qs -c noctalia-shell ipc call launcher toggle
bind = SUPER, W, exec, qs -c noctalia-shell ipc call controlCenter toggle
bind = SUPER, comma, exec, qs -c noctalia-shell ipc call settings toggle

bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

bind = SUPER SHIFT, h, movewindow, l
bind = SUPER SHIFT, l, movewindow, r
bind = SUPER SHIFT, k, movewindow, u
bind = SUPER SHIFT, j, movewindow, d

bind = SUPER CTRL, h, resizeactive, -50 0
bind = SUPER CTRL, l, resizeactive, 50 0
bind = SUPER CTRL, k, resizeactive, 0 -50
bind = SUPER CTRL, j, resizeactive, 0 50

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5 

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5

binde = , XF86AudioRaiseVolume, exec, qs -c noctalia-shell ipc call volume increase
binde = , XF86AudioLowerVolume, exec, qs -c noctalia-shell ipc call volume decrease
bind = , XF86AudioMute, exec, qs -c noctalia-shell ipc call volume muteOutput
bind = SUPER, X, exec, grim -g "$(slurp)" - | wl-copy
input{
   kb_layout = us,ru
   kb_options = grp:alt_shift_toggle
   sensitivity = -0.4
}

animations {
    enabled = yes
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1

    animation = windows, 1, 3, wind, popin 80%
    animation = windowsIn, 1, 3, winIn, popin 80%
    animation = windowsOut, 1, 3, winOut, popin 80%
    animation = fade, 1, 3, default
    animation = workspaces, 1, 3, wind, slide
}

general {
     gaps_in = 2
     gaps_out = 12
     border_size = 4
     layout = dwinde
     }     

decoration {
    rounding = 14
    blur {
        enabled = true
        size = 10
        passes = 3
        ignore_opacity = true  
        new_optimizations = true 
        vibrancy = 0.2
        popups = true
    }
    active_opacity = 0.9
    inactive_opacity = 0.9
    
    shadow {
        enabled = no
    }
    
    dim_inactive = false
    dim_strength = 0.0
}

cursor {
    no_hardware_cursors = true
    inactive_timeout = 0
}

source = /home/hihity/.config/hypr/noctalia/noctalia-colors.conf
